# Project
site_name: 'Branch documentation'
site_description: 'Branch documentation for mobile deep linking'
site_author: 'Branch'
site_url: 'https://docs.branch.io'
repo_name: 'Branch documentation'
repo_url: 'https://github.com/branchmetrics/docs'
edit_uri: 'edit/master/src/'
copyright: 'Copyright &copy; 2017 <a href="https://branch.io">Branch</a>'
site_favicon: img/favicon-96x96.png

# Files
theme: 'material'
theme_dir: 'lib/mkdocs-material/material'
docs_dir: 'src'
extra_css:
  - 'css/main.css'
extra_javascript:
  - 'js/router.js'
  - 'js/events.js'
  - 'js/modals.js'
  - 'js/images.js'
  - 'js/buttons.js'
  - 'js/progress.js'
  - 'js/tabs.js'
  - 'js/languages.js'
  - 'js/utils.js'
  - 'js/main.js'

# Extensions
markdown_extensions:
  - admonition:
  - codehilite: #(linenums=true)
  - footnotes:
  - toc(permalink=true):
  - meta:
  - pymdownx.github:
  - attr_list:
  - markdown_include.include:
      base_path: src/includes/

# Options
extra:
  logo: 'img/logo.svg'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'globe'
      link: 'https://branch.io'
    - type: 'github'
      link: 'https://github.com/branchmetrics/docs'
    - type: 'twitter'
      link: 'https://twitter.com/branchmetrics'
    - type: 'facebook'
      link: 'https://www.facebook.com/branchmetrics'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company-beta/3813083'
  disqus: 'branch-docs'
  sources:
    mixpanel: '47ec8ea9ac102b1370221dcda476091c'
    google:
      optimize: 'GTM-PCPBXCN'
      analytics: 'UA-53307642-1'
    facebook: '1040694199304729'
    munchkin: '315-FTT-121'
    linkedin: '21211'
    bizible: true
    demandbase: true
    quora: '247e840cafa44cae9ac4b50a0cc1965a'
    algolia:
      key: '887017d17a2c1e9490ad2c44caa7e817'
      index: 'branchmetrics'
      selector: '#algolia-doc-search'
      debug: true
      hits: 15
  nav_header:
    - index: 2
      title: Basic integration
    - index: 7
      title: Basic usage
    - index: 9
      title: Advanced usage
    - index: 18
      title: Resources
  nav_hidden: 'Hidden'
  is_visible:
    footer_floater_beta: false
    footer_floater_old_docs: false
    footer_nav: false
    header_git: false
    header_breadcrumb: true

# Pages
pages:
  - Getting started: index.md
  - Configure your dashboard: pages/dashboard/integrate.md
  - Configure your app:
    - iOS: pages/apps/ios.md
    - Android: pages/apps/android.md
    - Adobe AIR: pages/apps/adobe-air.md
    - Cordova PhoneGap Ionic: pages/apps/cordova-phonegap-ionic.md
    - mParticle Android: pages/apps/mparticle-android.md
    - mParticle iOS: pages/apps/mparticle-ios.md
    - Titanium: pages/apps/titanium.md
    - React Native: pages/apps/react-native.md
    - Unity: pages/apps/unity.md
    - Xamarin: pages/apps/xamarin.md
    - API: pages/apps/api.md
  - Configure your deep linking:
    - iOS Universal Links: pages/deep-linking/universal-links.md
    - Android App Links: pages/deep-linking/android-app-links.md
    - In-app deep link routing: pages/deep-linking/routing.md
  - Launch your app:
    - Apple App Store: pages/apps/ios-launch.md
    - Google Play: pages/apps/android-launch.md
  - Configure your website: pages/web/integrate.md
  - Create deep links: pages/links/integrate.md
  - Track analytics:
    - Dashboard analytics: pages/dashboard/analytics.md
    - Time zone support: pages/dashboard/timezone.md
  - Links on your website:
    - Deepviews: pages/web/deep-views.md
    - Journeys App Banners: pages/web/journeys.md
    - AMP Journeys: pages/web/amp-journeys.md
    - Text Me The App: pages/web/text-me-the-app.md
    - Hosted Deep Link Data: pages/web/hosted-data.md
  - Links in your paid ads:
    - Dynamic Product Feeds: pages/deep-linked-ads/dynamic-product-feeds.md
    - Branch Universal Ads: pages/deep-linked-ads/branch-universal-ads.md
    - Apple Search: pages/deep-linked-ads/apple.md
    - Doubleclick: pages/deep-linked-ads/doubleclick.md
    - Google: pages/deep-linked-ads/google-ads-overview.md
    - Facebook: pages/deep-linked-ads/facebook-ads-overview.md
    - Twitter: pages/deep-linked-ads/twitter.md
  - Links in your emails:
    - Get Started: pages/emails/get-started.md
    - Amazon SES: pages/emails/amazon-ses.md
    - Braze (formerly Appboy): pages/emails/braze.md
    - Blueshift: pages/emails/blueshift.md
    - Bronto: pages/emails/bronto.md
    - Campaign Monitor: pages/emails/campaign-monitor.md
    - Epsilon: pages/emails/epsilon.md
    - Kahuna: pages/emails/kahuna.md
    - Leanplum: pages/emails/leanplum.md
    - Mailgun: pages/emails/mailgun.md
    - Mailjet: pages/emails/mailjet.md
    - Mandrill: pages/emails/mandrill.md
    - PostUp: pages/emails/postup.md
    - Responsys: pages/emails/responsys.md
    - Sailthru: pages/emails/sailthru.md
    - Salesforce: pages/emails/salesforce.md
    - SendGrid: pages/emails/sendgrid.md
    - SparkPost: pages/emails/sparkpost.md
    - Vero: pages/emails/vero.md
    - Zeta: pages/emails/zeta.md
    - Support: pages/emails/support.md
    - Self Serve: pages/emails/self-serve.md
  - Links in push notifications: pages/advance/push-notifications.md
  - Links in organic search:
    - Firebase App Indexing: pages/organic-search/firebase.md
    - Spotlight Search: pages/organic-search/spotlight.md
    - General SEO Compatibility: pages/organic-search/branch-seo.md
  - Links for viral & referral:
    - Content sharing: pages/viral/content-sharing.md
    - Referral programs: pages/viral/referrals.md
    - Facebook App Invites: pages/viral/facebook-app-invites.md
  - Links in new app platforms:
    - Android Instant Apps: pages/app-to-app/android-instant-apps.md
    - iMessage Apps: pages/app-to-app/imessage-apps.md
  - Export Branch data:
    - Data Feeds:
      - Get Started: pages/exports/data-feeds.md
      - Data Integrations:
        - Get Started: pages/integrations/data-integrations.md
        - Adobe Analytics: pages/integrations/adobe-analytics.md
        - Adjust: pages/integrations/adjust.md
        - Amplitude: pages/integrations/amplitude.md
        - AppMetrica: pages/integrations/appmetrica.md
        - Appboy: pages/integrations/appboy.md
        - Appsflyer: pages/integrations/appsflyer.md
        - CleverTap: pages/integrations/clevertap.md
        - Fabric Answers: pages/integrations/fabric-answers.md
        - Google Analytics: pages/integrations/google-analytics.md
        - Kochava: pages/integrations/kochava.md
        - Localytics: pages/integrations/localytics.md
        - Mixpanel: pages/integrations/mixpanel.md
        - Tune: pages/integrations/tune.md
      - Data Export API: pages/exports/api-v3.md
      - Webhooks: pages/exports/ua-webhooks.md
  - Branch Matching Overview: pages/resources/matching.md
  - Validation Tools: pages/resources/validation-tools.md
  - Case Studies and Infographics: pages/resources/case-studies.md
  - Hidden:
    - Google Search App Install Ads: pages/deep-linked-ads/google-search-install-ads.md
    - Google Search App Engagement Ads: pages/deep-linked-ads/google-search-engagement-ads.md
    - Google Display App Install Ads: pages/deep-linked-ads/google-display-install-ads.md
    - Google Display App Engagement Ads: pages/deep-linked-ads/google-display-engagement-ads.md
    - Google Universal App Campaigns: pages/deep-linked-ads/google-uac.md
    - Google Search Network Ads: pages/deep-linked-ads/google-xplatform-search-ads.md
    - Google Display Network Ads: pages/deep-linked-ads/google-xplatform-display-ads.md
    - Google Adwords Conversion Setup: pages/deep-linked-ads/google-conversions.md
    - Google Video Ads: pages/deep-linked-ads/google-video-ads.md
    - Facebook App Install Ads: pages/deep-linked-ads/facebook-app-install-ads.md
    - Facebook Traffic and Conversion Ads: pages/deep-linked-ads/facebook-traffic-conversion-ads.md
    - Facebook Platform Ads: pages/deep-linked-ads/facebook-platform-ads.md
    - Facebook Dynamic Ads: pages/deep-linked-ads/facebook-dynamic-ads.md
    - V2 Event: pages/apps/v2event.md
    - People-Based Attribution: pages/dashboard/people-based-attribution.md
    - Enable Single Sign On: pages/dashboard/sso.md
    - Legacy Data Export API: pages/exports/api.md
    - Legacy Webhooks: pages/exports/webhooks.md
    - Event Ontology: pages/exports/event_ontology_data_schema.md
    - New Data Integrations: pages/integrations/faq.md
